
#######################################################################
###-------------------- Code for Simulation 1 ----------------------###
#######################################################################


## Source all necessary functions
source("core_functions.R")
source("simulation_functions.R")

## Load required packages
library(MASS)
library(gdata)
library(caret)
library(mclust)
library(phyclust)


## Run simulation on p=0.1,0.3,0.5,0.7,0.9
## WARNING: Time-consuming
out1 = sim1(0.1)
out3 = sim1(0.3)
out5 = sim1(0.5)
out7 = sim1(0.7)
out9 = sim1(0.9)

##################################################################
### All simulations results are available in "Results" folder. ###
##################################################################






    #########################################################
    ###################### Figure 1 #########################
    #########################################################

## Plot MCLUST and MCLUST-ME results for seed=7 and p=0.5

## Warning: seed=7 may not be present in a new simulation due to 
## the random sampling of seeds. If this is the case, please consider
## graphing datasets generated by other seeds. Simply replace "7" by
## the user's seed of choice.
load("Results/res_sim1_05.RData")
res5 = out$sim.result
seeds = out$seed
k = which(seeds==7) 
i = (k-1)*7+1
simrun7 = list(res.mcme=res5[[i]],res.mevvv=res5[[(i+1)]],z.ini=res5$z.ini,
  rand.samples=res5[[(i+3)]],errmat=res5[[(i+4)]],index=res5[[(i+5)]],k=res5[[(i+6)]])

tiff("Fig1.tiff",width=2090,height=1190,compression="lzw",res=250)
par(mfrow=c(1,2))
plot.boundary(simrun7,7)
par(mfrow=c(1,1))
dev.off()




    #########################################################
    ###################### Figure 2 #########################
    #########################################################

## Visualize classification uncertainties
tiff("Fig2.tiff",width=2090,height=1190,compression="lzw",res=250)
par(mfrow=c(1,2))
plot.uncr(7,out)
par(mfrow=c(1,1))
dev.off()







## Extract Rand and Fuzzy Rand indices
# p = 0.1
load("Results/res_sim1_01.RData")
tmp1 = out$rand.raw
r1.mcme = tmp1[,1]
r1.mevvv = tmp1[,4]
fr1.mcme = tmp1[,7]
fr1.mevvv = tmp1[,8]

# p = 0.3
load("Results/res_sim1_03.RData")
tmp3 = out$rand.raw
r3.mcme = tmp3[,1]
r3.mevvv = tmp3[,4]
fr3.mcme = tmp3[,7]
fr3.mevvv = tmp3[,8]

# p = 0.5
load("Results/res_sim1_05.RData")
tmp5 = out$rand.raw
r5.mcme = tmp5[,1]
r5.mevvv = tmp5[,4]
fr5.mcme = tmp5[,7]
fr5.mevvv = tmp5[,8]

# p = 0.7
load("Results/res_sim1_07.RData")
tmp7 = out$rand.raw
r7.mcme = tmp7[,1]
r7.mevvv = tmp7[,4]
fr7.mcme = tmp7[,7]
fr7.mevvv = tmp7[,8]

# p = 0.9
load("Results/res_sim1_09.RData")
tmp9 = out$rand.raw
r9.mcme = tmp9[,1]
r9.mevvv = tmp9[,4]
fr9.mcme = tmp9[,7]
fr9.mevvv = tmp9[,8]

rand.mcme = c(r1.mcme,r3.mcme,r5.mcme,r7.mcme,r9.mcme)
rand.mevvv = c(r1.mevvv,r3.mevvv,r5.mevvv,r7.mevvv,r9.mevvv)
frand.mcme = c(fr1.mcme,fr3.mcme,fr5.mcme,fr7.mcme,fr9.mcme)
frand.mevvv = c(fr1.mevvv,fr3.mevvv,fr5.mevvv,fr7.mevvv,fr9.mevvv)
group = c(rep(0.1,100),rep(0.3,100),rep(0.5,100),rep(0.7,100),rep(0.9,100))





    #########################################################
    ###################### Figure 3 #########################
    #########################################################

## Boxplot of individual Rand/Fuzzy Rand indices
tiff("Fig3.tiff",width=1580,height=1580,compression="lzw",res=250)
par(mfrow=c(2,2))
boxplot(rand.mcme~group,main="Rand, MCLUST-ME",xlab="proportion of obs with errors")
boxplot(rand.mevvv~group,main="Rand, MCLUST",xlab="proportion of obs with errors")
boxplot(frand.mcme~group,main="Fuzzy Rand, MCLUST-ME",xlab="proportion of obs with errors")
boxplot(frand.mevvv~group,main="Fuzzy Rand, MCLUST",xlab="proportion of obs with errors")
par(mfrow=c(1,1))
dev.off()




    #########################################################
    ###################### Figure 4 #########################
    #########################################################

## Boxplot of pairwise difference for all p
rand.diff = rand.mcme - rand.mevvv
frand.diff = frand.mcme - frand.mevvv

tiff("Fig4.tiff",width=2090,height=1180,compression="lzw",res=250)
par(mfrow=c(1,2))
boxplot(rand.diff~group,main="Rand index",xlab="proportion of obs with errors")
abline(0,0,lty="dashed")
boxplot(frand.diff~group,main="Rand index",xlab="proportion of obs with errors")
abline(0,0,lty="dashed")
par(mfrow=c(1,1))
dev.off()




    #########################################################
    ###################### Figure 5 #########################
    #########################################################

# Scatterplot for pairwise comparison when p=0.5
tiff("Fig5.tiff",width=2090,height=1180,compression="lzw",res=250)
par(mfrow=c(1,2))
plot(r5.mevvv,r5.mcme-r5.mevvv,ylab="MCLUST-ME--MCLUST",xlab="MCLUST",main="Rand Index")
abline(0,0,lty="dashed")

plot(fr5.mevvv,fr5.mcme-fr5.mevvv,ylab="MCLUST-ME--MCLUST",xlab="MCLUST",main="Fuzzy Rand Index")
abline(0,0,lty="dashed")
par(mfrow=c(1,1))
dev.off()


