#######################################################################
###-------------------- Code for Simulation 1 ----------------------###
#######################################################################

## 
setwd("D:/ongoing/Model-Based-Clustering-Research")

## Source all necessary functions
source("Code/core_functions.R")
source("Code/simulation_functions.R")

## Load required packages
library(MASS)
library(gdata)
library(caret)
library(mclust)
library(phyclust)


run.simulations = function() {
  ## Run simulation on p=0.1,0.3,0.5,0.7,0.9
  ## WARNING: Time-consuming
  out1 = sim1(0.1)
  out3 = sim1(0.3)
  out5 = sim1(0.5)
  out7 = sim1(0.7)
  out9 = sim1(0.9)
}

##################################################################
### All simulations results are available in "Results" folder. ###
##################################################################

###################### Figure 1 #########################
#########################################################

## Plot MCLUST and MCLUST-ME results for seed=7 and p=0.5

## Warning: seed=7 may not be present in a new simulation due to 
## the random sampling of seeds. If this is the case, please consider
## graphing datasets generated by other seeds. Simply replace "7" by
## the user's seed of choice.
load("Results/res_sim1_05.RData")
res5 = out$sim.result
seeds = out$seed
k = which(seeds==7) 
i = (k-1)*7+1
simrun7 = list(res.mcme=res5[[i]],res.mevvv=res5[[(i+1)]],z.ini=res5$z.ini,
               rand.samples=res5[[(i+3)]],errmat=res5[[(i+4)]],index=res5[[(i+5)]],k=res5[[(i+6)]])

tiff("Fig1.tiff",width=2090,height=1190,compression="lzw",res=250)
par(mfrow=c(1,2))
plot.boundary(simrun7,7)
par(mfrow=c(1,1))
dev.off()




#########################################################
###################### Figure 2 #########################
#########################################################

## Visualize classification uncertainties
tiff("Fig2.tiff",width=2090,height=1190,compression="lzw",res=250)
par(mfrow=c(1,2))
plot.uncr(7,out)
par(mfrow=c(1,1))
dev.off()











## Extract adjusted Rand index
get.ARI = function(filename){
  
  load(filename)
  
  tmp = out$sim.result
  
  get.label = function(z){
    out = numeric(nrow(z))
    for(i in 1:nrow(z)){
      out[i] = which(z[i,]==max(z[i,]))
    }
    return(out)
  }
  
  ARI.signif = function(A,B,M){
    
    ARI.obs = adjustedRandIndex(A, B)
    ARI.perm = numeric(M)
    for(i in 1:M){
      A.rand = sample(A)
      B.rand = sample(B)
      ARI.perm[i] = adjustedRandIndex(A.rand, B.rand)
    }
    
    m = mean(ARI.perm)
    v = var(ARI.perm)
    NARI.perm = (ARI.perm-m)/sqrt(v)
    NARI.obs = (ARI.obs-m)/sqrt(v)
    p.val = round(mean(NARI.perm>NARI.obs),3)
    return(p.val)
  }
  
  ARI.mcme = ARI.mevvv = pval.mcme = pval.mevvv = numeric(100)
  for(i in 1:100){
    k = 1+(i-1)*7
    rmcme = tmp[[k]]
    rmevvv = tmp[[(k+1)]]
    z.ini = tmp[[(k+2)]]
    zmcme = rmcme$z
    zmevvv = rmevvv$z
    label.mcme = get.label(zmcme)
    label.mevvv = get.label(zmevvv)
    label.true = get.label(z.ini)
    ARI.mcme[i] = adjustedRandIndex(label.mcme, label.true)
    ARI.mevvv[i] = adjustedRandIndex(label.mevvv, label.true)
    pval.mcme[i] = ARI.signif(label.mcme, label.true, 1000)
    pval.mevvv[i] = ARI.signif(label.mevvv, label.true, 1000)
  }
  
  ARI = data.frame(ARI.mcme=ARI.mcme,ARI.mevvv=ARI.mevvv,
                   pval.mcme=pval.mcme,pval.mevvv=pval.mevvv)
  
  return(ARI)  
}



rerun = FALSE;

if (rerun)  {
  
  ## 2020-02-03, we need to set a seed if we want the results to be reproducible!
  set.seed(999);
  
  # p = 0.1
  ari.01 = get.ARI("Results/res_sim1_01.RData")
  
  # p = 0.3
  ari.03 = get.ARI("Results/res_sim1_03.RData")
  
  # p = 0.5
  ari.05 = get.ARI("Results/res_sim1_05.RData")
  
  # p = 0.7
  ari.07 = get.ARI("Results/res_sim1_07.RData")
  
  # p = 0.9
  ari.09 = get.ARI("Results/res_sim1_09.RData")

ari.mcme = c(ari.01$ARI.mcme, ari.03$ARI.mcme, ari.05$ARI.mcme, 
             ari.07$ARI.mcme, ari.09$ARI.mcme)
ari.mevvv = c(ari.01$ARI.mevvv, ari.03$ARI.mevvv, ari.05$ARI.mevvv, 
              ari.07$ARI.mevvv, ari.09$ARI.mevvv)
group = c(rep(0.1,100),rep(0.3,100),rep(0.5,100),rep(0.7,100),rep(0.9,100))


file.results = sprintf("Results/res_sim_ari.%s.Rdata", Sys.Date());
save(ari.01, ari.03, ari.05, ari.07, ari.09, ari.mcme, ari.mevvv, group, file=file.results)

}


date = "2020-02-03";
file.results = sprintf("Results/res_sim_ari.%s.Rdata", date);
print(load(file.results))



## Use permutation test to test whether ARI is significantly different between two methods
paired.perm = function(x,y,M){
  
  d = x-y
  m0 = mean(d)
  
  # perform a one-sample randomization test on d
  # for the null hypothesis H0: mu_d = 0   vs H1 mu_d != 0  (i.e. two tailed)
  # here the test statistic is the mean
  rndmdist = replicate(M,mean((rbinom(length(d),1,.5)*2-1)*d))
  
  hist(rndmdist,main="Permuted mean difference")
  abline(v=m0,col="red")
  
  # two tailed p-value:
  pval = sum(rndmdist >= m0)/length(rndmdist)
  t.out = t.test(x-y,alternative="greater")
  t.pval = t.out$p.value
  
  cat(paste("Permuted p-value = ",round(pval,3),"\n","T-test p-value = ",round(t.pval,3),sep=""))
  
  return(pval)
}


diffpval.01 = paired.perm(ari.01$ARI.mcme,ari.01$ARI.mevvv,99999)
diffpval.03 = paired.perm(ari.03$ARI.mcme,ari.03$ARI.mevvv,99999)
diffpval.05 = paired.perm(ari.05$ARI.mcme,ari.05$ARI.mevvv,99999)
diffpval.07 = paired.perm(ari.07$ARI.mcme,ari.07$ARI.mevvv,99999)
diffpval.09 = paired.perm(ari.09$ARI.mcme,ari.09$ARI.mevvv,99999)


# Add significance flag based on ARI p-values
add.sigfl = function(data){
  
  pval.mcme = data$pval.mcme
  pval.mevvv = data$pval.mevvv
  sigfl = numeric(nrow(data))
  for(i in 1:nrow(data)){
    if(pval.mcme[i]<0.05 && pval.mevvv[i]>=0.05){
      sigfl[i] = 1
    }else if(pval.mcme[i]>=0.05 && pval.mevvv[i]<0.05){
      sigfl[i] = 2
    }else if(pval.mcme[i]<0.05 && pval.mevvv[i]<0.05){
      sigfl[i] = 3
    }else{
      sigfl[i] = 4
    }
  }
  data$sigfl = sigfl
  return(data)
}

ARI1 = add.sigfl(ari.01)
ARI3 = add.sigfl(ari.03)
ARI5 = add.sigfl(ari.05)
ARI7 = add.sigfl(ari.07)
ARI9 = add.sigfl(ari.09)


#########################################################
###################### Figure 3 #########################
#########################################################

## Boxplot of individual Rand/Fuzzy Rand indices
png("Graphs/Fig3.png",width=2000,height=1000,res=200)

par(mfrow=c(1,2))
boxplot(ari.mcme~group,main="ARI, MCLUST-ME",xlab="Proportion of erroneous observations")
boxplot(ari.mevvv~group,main="ARI, MCLUST",xlab="Proportion of erroneous observations")
par(mfrow=c(1,1))

dev.off()


## Updated 2020-02-03
file.png = sprintf("Graphs/Figure3.%s.png", Sys.Date());
png(file.png, width=1500,height=1000,res=200)

## Paired boxplot of ARI

ari = list(
  ari.01$ARI.mcme, ari.01$ARI.mevvv, 
  ari.03$ARI.mcme, ari.03$ARI.mevvv,
  ari.05$ARI.mcme, ari.05$ARI.mevvv, 
  ari.07$ARI.mcme, ari.07$ARI.mevvv,
  ari.09$ARI.mcme, ari.09$ARI.mevvv);
boxplot(ari, 
        at=c(1,2, 4,5, 7,8, 10,11, 13,14),
        names=c("0.1", "", "0.3", "", "0.5","", "0.7","", "0.9",""),
        col = rep(c("magenta","darkcyan"), 5),
        main="Adjusted Rand Index (ARI), MCLUST-ME vs MCLUST",
        xlab="Proportion of erroneous observations",
        ylab="ARI"
        );
dev.off()


#########################################################
###################### Figure 4 #########################
#########################################################

## Updated: 2020-02-03
## Boxplot of pairwise difference for all p
ari.diff = ari.mcme - ari.mevvv

png("Graphs/Figure4.png",width=1500,height=1500,res=200)

boxplot(ari.diff~group,main="Pairwise ARI Differences",
        xlab="Proportion of erroneous observations",
        ylab="Pairwise differences in ARI")
abline(h=0,lty="dashed")

dev.off()




#########################################################
###################### Figure 5 #########################
#########################################################

# Scatterplot for pairwise comparison when p=0.5
png("Graphs/Fig5.png",width=1500,height=1500,res=200)
plot(ari.05$ARI.mevvv,ari.05$ARI.mcme-ari.05$ARI.mevvv,ylab="MCLUST-ME--MCLUST",xlab="MCLUST",main="Pairwise ARI Differences")
abline(h=0,lty="dashed")
dev.off()




#########################################################
###################### Figure ? #########################
#########################################################

# Scatterplot showing pairs of ARI values, with markers for [whether ARI>0 significantly]
pairscatter.sigfl = function(data,title){
  
  ARI.mcme = data$ARI.mcme
  ARI.mevvv = data$ARI.mevvv
  sigfl = data$sigfl
  
  upper = max(c(ARI.mcme, ARI.mevvv))+0.01
  lower = min(c(ARI.mcme, ARI.mevvv))-0.01
  plot(ARI.mevvv, ARI.mcme, xlim=c(lower,upper), ylim=c(lower,upper),
       xlab="MCLUST ARI",ylab="MCLUST-ME ARI",
       main=title,
       col=c("red","yellow","orange","green")[sigfl],
       pch=16)
  abline(0,1,lty="dashed")
  legend("bottomright",legend=c("MCLUST-ME sig. >0","MCLUST sig. >0","Both sig. >0","Neither sig. >0"),
         col=c("red","yellow","orange","green"),pch=16,cex=0.7)
}

png("Graphs/scatter_sigfl.png",width=2250,height=1500,res=200)
par(mfrow=c(2,3))
pairscatter.sigfl(ARI1,title=expression(paste(eta," = 0.1",sep="")))
pairscatter.sigfl(ARI3,title=expression(paste(eta," = 0.3",sep="")))
pairscatter.sigfl(ARI5,title=expression(paste(eta," = 0.5",sep="")))
pairscatter.sigfl(ARI7,title=expression(paste(eta," = 0.7",sep="")))
pairscatter.sigfl(ARI9,title=expression(paste(eta," = 0.9",sep="")))
par(mfrow=c(1,1))
dev.off()



























