
#######################################################################
###-------------------- Code for Simulation 2 ----------------------###
#######################################################################


## Run simulation on p=0.1,0.3,0.5,0.7,0.9
## WARNING: Time-consuming
out1 = sim2(0.1)
out3 = sim2(0.3)
out5 = sim2(0.5)
out7 = sim2(0.7)
out9 = sim2(0.9)

#########################################################
### All simulations results are available in:         ###
### "Simulations/2-Cluster Simulation/Sim 2/Results". ###
#########################################################






    #########################################################
    ###################### Figure 6 #########################
    #########################################################

## Plot MCLUST and MCLUST-ME results for seed=2 and p=0.5

## Warning: seed=2 may not be present in a new simulation due to 
## the random sampling of seeds. If this is the case, please consider
## graphing datasets generated by other seeds. Simply replace "2" by
## the user's seed of choice.

res5 = out5$sim.result
seeds = out5$seed
k = which(seeds==2) 
i = (k-1)*7+1
simrun2 = list(res.mcme=res5[[i]],res.mevvv=res5[[(i+1)]],z.ini=res5$z.ini[[(i+2)]],
  rand.samples=res5[[(i+3)]],errmat=res5[[(i+4)]],index=res5[[(i+5)]],k=res5[[(i+6)]])

par(mfrow=c(1,2))
plot.boundary(simrun2,2)
par(mfrow=c(1,1))






## Extract Rand and Fuzzy Rand indices
# p = 0.1
tmp1 = out1$rand.raw
r1.mcme = tmp1[,1]
r1.mevvv = tmp1[,4]
fr1.mcme = tmp1[,7]
fr1.mevvv = tmp1[,8]

# p = 0.3
tmp3 = out3$rand.raw
r3.mcme = tmp3[,1]
r3.mevvv = tmp3[,4]
fr3.mcme = tmp3[,7]
fr3.mevvv = tmp3[,8]

# p = 0.5
tmp5 = out5$rand.raw
r5.mcme = tmp5[,1]
r5.mevvv = tmp5[,4]
fr5.mcme = tmp5[,7]
fr5.mevvv = tmp5[,8]

# p = 0.7
tmp7 = out7$rand.raw
r7.mcme = tmp7[,1]
r7.mevvv = tmp7[,4]
fr7.mcme = tmp7[,7]
fr7.mevvv = tmp7[,8]

# p = 0.9
tmp9 = out9$rand.raw
r9.mcme = tmp9[,1]
r9.mevvv = tmp9[,4]
fr9.mcme = tmp9[,7]
fr9.mevvv = tmp9[,8]

rand.mcme = c(r1.mcme,r3.mcme,r5.mcme,r7.mcme,r9.mcme)
rand.mevvv = c(r1.mevvv,r3.mevvv,r5.mevvv,r7.mevvv,r9.mevvv)
frand.mcme = c(fr1.mcme,fr3.mcme,fr5.mcme,fr7.mcme,fr9.mcme)
frand.mevvv = c(fr1.mevvv,fr3.mevvv,fr5.mevvv,fr7.mevvv,fr9.mevvv)
group = c(rep(0.1,100),rep(0.3,100),rep(0.5,100),rep(0.7,100),rep(0.9,100))





    #########################################################
    ###################### Figure 7 #########################
    #########################################################

## Boxplot of individual Rand/Fuzzy Rand indices
par(mfrow=c(2,2))
boxplot(rand.mcme~group,main="Rand, MCLUST-ME",xlab="proportion of obs with errors")
boxplot(rand.mevvv~group,main="Rand, MCLUST",xlab="proportion of obs with errors")
boxplot(frand.mcme~group,main="Fuzzy Rand, MCLUST-ME",xlab="proportion of obs with errors")
boxplot(frand.mevvv~group,main="Fuzzy Rand, MCLUST",xlab="proportion of obs with errors")
par(mfrow=c(1,1))





    #########################################################
    ###################### Figure 8 #########################
    #########################################################

rand.diff = rand.mcme - rand.mevvv
frand.diff = frand.mcme - frand.mevvv

par(mfrow=c(2,2))

## Pairwise difference for all p
boxplot(rand.diff~group,main="Rand index",xlab="proportion of obs with errors")
abline(0,0,lty="dashed")
boxplot(frand.diff~group,main="Rand index",xlab="proportion of obs with errors")
abline(0,0,lty="dashed")

# Scatterplot for pairwise comparison when p=0.5
plot(r5.mevvv,r5.mcme-r5.mevvv)
abline(0,0,lty="dashed")
plot(fr5.mevvv,fr5.mcme-fr5.mevvv)
abline(0,0,lty="dashed")
par(mfrow=c(1,1))


